// front/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import './index.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

console.log(import.meta.env)

const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
  },
])

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>,
)

// front-solid/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web'
import { Router, Route } from '@solidjs/router'
import 'solid-devtools'

import './index.css'
import App from './App'
import { OAuth } from './pages'

const root = document.getElementById('root')

render(() => 
<Router>
    <Route path="/" component={App} />
    <Route path="/OAuth" component={OAuth} />
</Router>, root!)
